import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HeroSection from "@/components/home/HeroSection";
import DeliveryWorks from "@/components/home/DeliveryWorks";
import CustomerFavorites from "@/components/home/CustomerFavorites";
import Banner from "@/components/home/Banner";
import ImageGallery from "@/components/home/ImageGallery";
import Articles from "@/components/home/Articles";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeroSection />
        <DeliveryWorks />
        <CustomerFavorites />
        <Banner />
        <ImageGallery />
        <Articles />
      </div>
    </>
  );
}
